[package]
name = "lisp"
version = "0.1.0"
authors = ["Dennis Nemec <dennis.nemec@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.6.0", features=["full"]}